### ISSUE TITLE
Feature request: Improved support Atlas.ti exports

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailDatasetBrowser#10]
Currently, there is no dedicated export method for Atlas.ti. Technically, exporting plain text, the current exporting method, works, but a lot of irrelevant data is added as well and it doesn't scale well. (I accidentally tried to import a the text file containing 100 mailing threads and the Atlas.ti web-app crashed.)
Therefore, it would be nice if we could add a dedicated export method for Atlas.ti. 

I did some minor exploration on how to do this just now, and it doesn't seem completely trivial for which I left it for what it is. 
@andrewlalis, I believe Mohamed asked you about this feature as well (or he's going to still). Are you planning on tackling this issue (soon-ish), or can I jump on it?

**Comment by andrewlalis** [comment]
I'm not familiar with Atlas.ti or what sort of file format it would expect for exports, but if you can link me to some document/rfc explaining that, I can look into it this afternoon.

**Comment by wmeijer221** [comment]
I couldn't find any formal documentation on the format or any dev toolkits. However, I did take a look at a random ``.atlproj`` file. And it seems like it's a spruced up ``.zip`` file that uses ``HTML`` files to keep track of its files, labels, and groups.

**Comment by wmeijer221** [comment]
In the meantime, I made a workaround for this in [my fork](https://github.com/wmeijer221/EmailDatasetBrowser/tree/pdf_export). I'm not making a PR for this (yet), though, since it works a bit unintuitive. (I wonkily added it using the ``ExportLuceneSearchAction``, but it's not the neatest way to resolve this.)

If we want to go full future-proof on this exporting thing, it's probably best if we add some sort of "export panel" in which you can select specific export targets and can set specific settings for that. I'm not sure if it's worth the hassle though.

**Comment by wmeijer221** [comment]
Just got a response from the atlas people; they're not planning on sharing the bundle format with anyone, so I think .txt, .docx, or .pdf support will be as far as it goes.

**Comment by andrewlalis** [comment]
If you want to add export capabilities, I would prefer if they be added to the EmailIndexer, specifically in the `data.export` package, since I've already provided a simple framework for export which uses futures which are somewhat useful for the UI aspect. And additionally, I want to keep data processing out of the scope of the browser app, since it is simply an interface for interacting with the data.
