### ISSUE TITLE
How does downloading emails in the GUI work? 

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailDatasetBrowser#11]
I tried downloading emails from the [apache mailing archive](https://lists.apache.org/), however, either get an error, the download does seemingly nothing or it downloads nothing. Hence, my question. 
Additionally, when it does do something, it doesn't only handles, like 10-ish months, which is not what I put in the settings at all.

Thanks!

**Comment by andrewlalis** [comment]
![image](https://user-images.githubusercontent.com/9953867/168750929-3f9ab318-99ba-4204-9f62-2c9a04383e46.png)

For example, in this screenshot, I'd like to download the last 10 years of emails from the Apache Accumulo project. So then, I would download the emails like this:

![image](https://user-images.githubusercontent.com/9953867/168751769-81aace27-8330-4220-92eb-1995952b53be.png)

What I think you might be seeing with the "10-ish months" is that the fetcher will quit after attempting to retrieve 10 consecutive months of emails where there are none. You can see exactly what's going on [here](https://github.com/ArchitecturalKnowledgeAnalysis/EmailDownloader/blob/main/src/main/java/nl/andrewl/emaildownloader/ApacheMailingListFetcher.java). The reason for this is that I've previously been IP-banned by apache for scraping their jira issues too quickly, so I'm taking a conservative approach here and using a 1-second interval between downloads, and quitting once it appears that there's no point in continuing.

However, if it's still not clear what's going on, you can send me the exact info you filled into the download popup and I can debug the scenario.

**Comment by wmeijer221** [comment]
Right! I was doing something completely different xD
Thanks!
