### ISSUE TITLE
Bug: Opening dataset while another one is open freezes client.

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailDatasetBrowser#17]
When you have dataset open, and then proceed to open another one, the app freezes. If you manually close it first, it works just fine. 
There are two variants of this bug, if you open another dataset, it freezes while opening. If you open the same dataset, it freezes while closing. In both cases it opens the progress dialog, but never progresses beyond that.

This can probably just be fixed by closing the dataset first in ``DatasetOpenAction``.
I noticed that the ``CloseDatasetAction`` doesn't actually contain the logic for closing either, as it's included in ``EmailDatasetBrowser``. It'd probably be a worthwhile endeavor to move this logic too when fixing this bug.

**Comment by andrewlalis** [comment]
Fixed as of version 2.7.4.
