### ISSUE TITLE
Feature Request: Double check panel when exporting to an existing .zip file

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailDatasetBrowser#26]
I think it's a very smart idea to add a double-check feature when you select and existing .zip file when exporting the entire dataset. The reason? I gave myself a minor heart attack just now, as I almost replaced a folder I really can't afford to delete.

**Comment by andrewlalis** [comment]
Good idea. I've added that in v2.11.0, which should have a release shortly, and hopefully you can merge it without conflict into your pull request branch.
