### ISSUE TITLE
Feature Request: Auto load top email when executing new search. 

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailDatasetBrowser#27]
Currently, when executing a new search, the email you selected last (i.e. an email of your previous query) is still visualized (and is scrolled back to the top). This is confusing, as it feels like a new email loaded, whereas it didn't -- which is bad for usability. 
I think automatically loading the first email of your new search query would solve this problem. (And just display nothing when there are no results.)

**Comment by andrewlalis** [comment]
Added this, for both the simple browse and lucene search panels, in v2.12.1
