### ISSUE TITLE
Bug: Tags with commas can't be removed

### ISSUE THREAD

**Issue by wmeijer221** [ArchitecturalKnowledgeAnalysis/EmailDatasetBrowser#5]
Whenever you add a tag that has a comma in it (e.g. ``Something, Something Else``), two tags are added ``Something`` and `` Something Else``. Neither of these can be removed. 
Additionally, in the list of tags you can select from, it is still offered as one tag ``Something, Something Else``. If you add that to an email, the two separate tags are added again (which you then can't remove).

**Comment by andrewlalis** [comment]
Ah, this is indeed a bug with the internal EmailIndexer library, with how it fetches tags using a comma-delimited group aggregation. I see your PR mitigates this by forbidding the use of commas, and I'll probably just merge that in the short term, but I expect that if/when I extract tags as fully-fledged entities (thus removing eager loading of tags), that this bug will be removed in the EmailIndexer library.
